# frozen_string_literal: true

source 'https://rubygems.org'

# xcodeproj 1.27.0 has a type-checking regression that crashes pod install
# when parsing PBXFileReference entries in Flutter's default project.pbxproj.
# Pin to 1.26.0 until the fix is released.
# Ref: https://github.com/CocoaPods/CocoaPods/issues/12569
gem 'xcodeproj', '= 1.26.0'

gem 'cocoapods', '~> 1.16'
